- name: variable
  hosts: local
  connection: local
  vars:
  COURSE: aws
  DURATION: 120 hours
  STARTDATE: 28th april
  ENDDATE: august 28th
  tasks:
   - name: print variable
     ansible.builtin.debug:
      msg: "Hello good evening course:{{ COURSE }}, duration: {{ DURATION }}, startdate:  {{ STARTDATE }}, enddate: {{ ENDDATE }}"
